module7-task1 | homework
htmlacademy-javascript/2166307-kekstagram-28 pull request #6
Opened 2023-03-22 09:22 UTC by AndrewPlatonov888

Добрый день, прошу принять дз7.

2023-03-22 13:04 UTC, vindimm requested changes
Советую в `main.js` импортировать функцию `createDescriptionArr` и там создавать объект с данными. И уже эти данные в виде `const = thumbnails` экспортировать из `main.js`. Так логичнее потому что в будущем в `main.js` будем получать данные от сервера.

Названия модулей выглядят немного странно. `thumbnail-master.js` можно переименовать просто в `thumbnails.js`. Но это необязательно.

2023-03-23 07:47 UTC, AndrewPlatonov888 commented on js/thumbnail-master.js
> +const thumbnailsArr = createDescriptionArr(25);
Все будет исправлено! :)

2023-03-23 11:52 UTC, AndrewPlatonov888 commented on js/utils.js
Пришлось немного подправить эту функцию, т.к. в исходном виде она выдавала массив до 100 комментариев, а если больше тогда загрузка ЦП компа стремительно росла до 100% .
(просто задавал максимальное кол-во комментов  3,4,5, 10, 100 и обычно на 5 все слетало комп переходил в состояние перегрева; вот разобрался все-таки почему это происходило).

2023-03-23 15:43 UTC, vindimm approved these changes
Все хорошо. Импорты разных модулей в `main.js` можно убрать. Лучше экспортировать функции а не модули целиком.

2023-03-23 15:44 UTC, merged