module8-task1 | homework
htmlacademy-javascript/2166307-kekstagram-28 pull request #7
Opened 2023-03-27 07:21 UTC by AndrewPlatonov888

Добрый день,
прошу принять дз. 8 часть1

2023-03-27 17:14 UTC, vindimm requested changes
В целом - хорошо, но баг нужно устранить, когда мимо по счетчику лайков кликаешь.
Название `enlargedThumbnail` можно оставить - критериям соответствует. Но варианты `bigPicture` `fullPhoto` выглядят лаконичнее

2023-03-27 19:33 UTC, AndrewPlatonov888 commented on js/thumbnails-enlarger.js
> +  if (evt.target.parentElement.tagName === 'A' && evt.target.parentElement.hasAttributes('data-thumbnail-id')) {
предлагаю в picture___info сделать  pointer-events: none;
и весь баг решен!

2023-03-27 19:33 UTC, AndrewPlatonov888 commented on js/thumbnails-enlarger.js
> +function openThumbnail(evt) {
хорошо, так и сделал

2023-03-27 20:09 UTC, AndrewPlatonov888 commented on js/testdata-generator.js
> +const PHOTO_DESCRIPTIONS_COUNT = 26;
нашел ещё один потерянный квадратик. он был вместо заглушки в контейнере для больших фото. решил сохранить его :)

2023-03-27 20:11 UTC, AndrewPlatonov888 commented on js/thumbnails-enlarger.js
> +function renderComments(arr) {
принято

2023-03-28 06:47 UTC, vindimm commented on js/thumbnails-enlarger.js
> +  if (evt.target.parentElement.tagName === 'A' && evt.target.parentElement.hasAttributes('data-thumbnail-id')) {
Это хорошо что ты предлагаешь и знаешь разные способы. Но какой смысл менять CSS, делать код более зависимым от верстки. Выглядит как 'bad practice'. Но, согласен, работает.

2023-03-28 06:51 UTC, vindimm requested changes
в файле `js/thumbnails-enlarger.js` нужно тоже исправить название функции на 16 строке. Линтер на нее ругается и закрытие по `Esc` не работает.

2023-03-28 17:06 UTC, AndrewPlatonov888 commented on js/thumbnails-enlarger.js
> +  if (evt.target.parentElement.tagName === 'A' && evt.target.parentElement.hasAttributes('data-thumbnail-id')) {
Думаю, что подобный "проходной" js-код зависит от верстки, ровно настолько, насколько верстка от этого кода. Они взаимозависимы. Здесь важно найти золотую середину, и не загонятся ложными целями, а то так можно вообще всю разметку запихнуть в js - чтобы идеала по независимости достичь. А верстальщик, чёнить ляпнет завтра новое и всё -  кирдык :)
https://habr.com/ru/post/144611/  - такая прикольная статья из доп материалов - там разные принципы программирования. Один из принципов - KISS - keep it simple stupid (делайте вещи проще) - он мне очень понравился. Считаю js - типа тяжелой артилерией, нужной там, где HTML/CSSом тяжело решить или невозможно; если мы можем одним штрихом в CSS избежать каких-то функций/вызовов в js - это можно только приветствовать. Элемент явно носит декоративно-информационный характер - подтвердили это, сделав его прозрачным.

2023-03-28 17:47 UTC, AndrewPlatonov888 commented on js/thumbnails-enlarger.js
> +    const targetParent = evt.target.parentElement;
(я умею им пользоваться :) )

2023-03-29 07:15 UTC, merged